/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// C version for linuxcnc adapted by \author Frank Tkalcevic
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     Http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 68 generated on 2013-11-14 13:06:54.380140
/// To compile with gcc:
///     gcc ik.c -lm
/// To compile without any main function as a shared object (might need -llapack):
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp

#define IKFAST_HAS_LIBRARY
#define IKFAST_NUM_DOF 4
#define IKFAST_NUM_JOINTS 4
#define IKFAST_NUM_FREE_VARS 0

#include "ikfast_c.h" // found inside share/openrave-X.Y/python/ikfast_c.h

// check if the included ikfast version matches what this file was compiled with
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
IKFAST_COMPILE_ASSERT(IKFAST_VERSION==68);

#include <math.h>
#include <float.h>
#include <stdlib.h>
#include <stddef.h>
#include <complex.h>


#define IKFAST_STRINGIZE2(s) #s
#define IKFAST_STRINGIZE(s) IKFAST_STRINGIZE2(s)

#ifndef IKFAST_ASSERT
#include <stdio.h>
#include <stdlib.h>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { fprintf( stderr, "ikfast exception: " __FILE__ ":" IKFAST_STRINGIZE(__LINE__) ": " IKFAST_STRINGIZE(_PRETTY_FUNCTION__) ": Assertion '"  #b "' failed" ); exit(-1); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  ((IkReal)6.28318530717959)
#define IKPI  ((IkReal)3.14159265358979)
#define IKPI_2  ((IkReal)1.57079632679490)

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#ifndef isinf
#define isinf _isinf
#endif
#ifndef isfinite
#define isfinite _isfinite
#endif
#endif // _MSC_VER

// lapack routines
void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
void zgetrf_ (const int* m, const int* n, double complex * a, const int* lda, int* ipiv, int* info);
void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);


inline double IKabs(double f) { return fabs(f); }

inline double IKsqr(double f) { return f*f; }

inline double IKlog(double f) { return log(f); }

// allows asin and acos to exceed 1
#ifndef IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)2e-6)
#endif

// used to check input to atan2 for degenerate cases
#ifndef IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)2e-6)
#endif

// minimum distance of separate solutions
#ifndef IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#endif

// there are checkpoints in ikfast that are evaluated to make sure they are 0. This threshold speicfies by how much they can deviate
#ifndef IKFAST_EVALCOND_THRESH
#define IKFAST_EVALCOND_THRESH ((IkReal)0.000005)
#endif


inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline double IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0;
return acos(f);
}
inline double IKsin(double f) { return sin(f); }
inline double IKcos(double f) { return cos(f); }
inline double IKtan(double f) { return tan(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline double IKatan2Simple(double fy, double fx) { return atan2(fy,fx); }
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2(fy,fx);
}

struct CheckValue
{
    IkReal value;
    bool valid;
};
typedef struct CheckValue CheckValue;

inline CheckValue IKatan2WithCheck(IkReal fy, IkReal fx, IkReal epsilon)
{
    CheckValue ret;
    ret.valid = false;
    ret.value = 0;
    if( !isnan(fy) && !isnan(fx) ) {
        if( IKabs(fy) >= IKFAST_ATAN2_MAGTHRESH || IKabs(fx) > IKFAST_ATAN2_MAGTHRESH ) {
            ret.value = IKatan2Simple(fy,fx);
            ret.valid = true;
        }
    }
    return ret;
}

inline double IKsign(double f) {
    if( f > 0 ) {
        return 1.0;
    }
    else if( f < 0 ) {
        return -1.0;
    }
    return 0;
}

inline CheckValue IKPowWithIntegerCheck(IkReal f, int n)
{
    CheckValue ret;
    ret.valid = true;
    if( n == 0 ) {
        ret.value = 1.0;
        return ret;
    }
    else if( n == 1 )
    {
        ret.value = f;
        return ret;
    }
    else if( n < 0 )
    {
        if( f == 0 )
        {
            ret.valid = false;
            ret.value = (IkReal)1.0e30;
            return ret;
        }
        if( n == -1 ) {
            ret.value = (IkReal)(1.0)/f;
            return ret;
        }
    }

    int num = n > 0 ? n : -n;
    if( num == 2 ) {
        ret.value = f*f;
    }
    else if( num == 3 ) {
        ret.value = f*f*f;
    }
    else {
        ret.value = 1.0;
        while(num>0) {
            if( num & 1 ) {
                ret.value *= f;
            }
            num >>= 1;
            f *= f;
        }
    }
    
    if( n < 0 ) {
        ret.value = (IkReal)(1.0)/ret.value;
    }
    return ret;
}


static inline bool checkconsistency12(const IkReal* Breal)
{
    IkReal norm = 0.1;
    int i;
    for(i = 0; i < 11; ++i) {
        norm += IKabs(Breal[i]);
    }
    IkReal tol = 1e-6*norm; // have to increase the threshold since many computations are involved
    return IKabs(Breal[0]*Breal[0]-Breal[1]) < tol && IKabs(Breal[0]*Breal[2]-Breal[3]) < tol && IKabs(Breal[1]*Breal[2]-Breal[4]) < tol && IKabs(Breal[2]*Breal[2]-Breal[5]) < tol && IKabs(Breal[0]*Breal[5]-Breal[6]) < tol && IKabs(Breal[1]*Breal[5]-Breal[7]) < tol && IKabs(Breal[2]*Breal[5]-Breal[8]) < tol && IKabs(Breal[0]*Breal[8]-Breal[9]) < tol && IKabs(Breal[1]*Breal[8]-Breal[10]) < tol;
}

/// \brief Solve the det Ax^2+Bx+C = 0 problem using the Manocha and Canny method (1994)
///
/// matcoeffs is of length 54*3, for 3 matrices
static inline void solvedialyticpoly12qep(const IkReal* matcoeffs, IkReal* rawroots, int *numroots)
{
    const IkReal tol = 128.0*DBL_EPSILON;
    static IkReal IKFAST_ALIGNED16(M[24*24]);
    memset( M, 0, sizeof(M) );
    static IkReal IKFAST_ALIGNED16(A[12*12]);
    static IkReal IKFAST_ALIGNED16(work[24*24*23]);
    int ipiv[12];
    int info, coeffindex;
    const int worksize=24*24*23;
    const int matrixdim = 12;
    const int matrixdim2 = 24;
    *numroots = 0;
    // first setup M = [0 I; -C -B] and A
    coeffindex = 0;
    int j,k;
    for(j = 0; j < 6; ++j) {
        for(k = 0; k < 9; ++k) {
            M[matrixdim+(j+6)+2*matrixdim*k] = M[matrixdim+j+2*matrixdim*(k+3)] = -matcoeffs[coeffindex++];
        }
    }
    for(j = 0; j < 6; ++j) {
        for(k = 0; k < 9; ++k) {
            M[matrixdim+(j+6)+2*matrixdim*k+matrixdim*2*matrixdim] = M[matrixdim+j+2*matrixdim*(k+3)+matrixdim*2*matrixdim] = -matcoeffs[coeffindex++];
        }
    }
    for(j = 0; j < 6; ++j) {
        for(k = 0; k < 9; ++k) {
            A[(j+6)+matrixdim*k] = A[j+matrixdim*(k+3)] = matcoeffs[coeffindex++];
        }
        for(k = 0; k < 3; ++k) {
            A[j+matrixdim*k] = A[(j+6)+matrixdim*(k+9)] = 0;
        }
    }
    static const IkReal lfpossibilities[4][4] = {{1,-1,1,1},{1,0,-2,1},{1,1,2,0},{1,-1,4,1}};
    int lfindex = -1;
    bool bsingular = true;
    do {
        dgetrf_(&matrixdim,&matrixdim,A,&matrixdim,&ipiv[0],&info);
        if( info == 0 ) {
            bsingular = false;
            for(j = 0; j < matrixdim; ++j) {
                if( IKabs(A[j*matrixdim+j]) < 100*tol ) {
                    bsingular = true;
                    break;
                }
            }
            if( !bsingular ) {
                break;
            }
        }
        if( lfindex == 3 ) {
            break;
        }
        // transform by the linear functional
        lfindex++;
        const IkReal* lf = lfpossibilities[lfindex];
        // have to reinitialize A
        coeffindex = 0;
        for(j = 0; j < 6; ++j) {
            for(k = 0; k < 9; ++k) {
                IkReal a = matcoeffs[coeffindex+108], b = matcoeffs[coeffindex+54], c = matcoeffs[coeffindex];
                A[(j+6)+matrixdim*k] = A[j+matrixdim*(k+3)] = lf[0]*lf[0]*a+lf[0]*lf[2]*b+lf[2]*lf[2]*c;
                M[matrixdim+(j+6)+2*matrixdim*k] = M[matrixdim+j+2*matrixdim*(k+3)] = -(lf[1]*lf[1]*a + lf[1]*lf[3]*b + lf[3]*lf[3]*c);
                M[matrixdim+(j+6)+2*matrixdim*k+matrixdim*2*matrixdim] = M[matrixdim+j+2*matrixdim*(k+3)+matrixdim*2*matrixdim] = -(2*lf[0]*lf[1]*a + (lf[0]*lf[3]+lf[1]*lf[2])*b + 2*lf[2]*lf[3]*c);
                coeffindex++;
            }
            for(k = 0; k < 3; ++k) {
                A[j+matrixdim*k] = A[(j+6)+matrixdim*(k+9)] = 0;
            }
        }
    } while(lfindex<4);

    if( bsingular ) {
        return;
    }
    dgetrs_("No transpose", &matrixdim, &matrixdim2, A, &matrixdim, &ipiv[0], &M[matrixdim], &matrixdim2, &info);
    if( info != 0 ) {
        return;
    }

    // set identity in upper corner
    for(j = 0; j < matrixdim; ++j) {
        M[matrixdim*2*matrixdim+j+matrixdim*2*j] = 1;
    }
    static IkReal IKFAST_ALIGNED16(wr[24]);
    static IkReal IKFAST_ALIGNED16(wi[24]);
    static IkReal IKFAST_ALIGNED16(vr[24*24]);
    int one=1;
    dgeev_("N", "V", &matrixdim2, M, &matrixdim2, wr, wi,NULL, &one, vr, &matrixdim2, work, &worksize, &info);
    if( info != 0 ) {
        return;
    }
    IkReal Breal[matrixdim-1];
    int i;
    for(i = 0; i < matrixdim2; ++i) {
        if( IKabs(wi[i]) < tol*100 ) {
            IkReal* ev = vr+matrixdim2*i;
            if( IKabs(wr[i]) > 1 ) {
                ev += matrixdim;
            }
            // consistency has to be checked!!
            if( IKabs(ev[0]) < tol ) {
                continue;
            }
            IkReal iconst = 1/ev[0];
            for(j = 1; j < matrixdim; ++j) {
                Breal[j-1] = ev[j]*iconst;
            }
            if( checkconsistency12(Breal) ) {
                if( lfindex >= 0 ) {
                    const IkReal* lf = lfpossibilities[lfindex];
                    rawroots[(*numroots)++] = (wr[i]*lf[0]+lf[1])/(wr[i]*lf[2]+lf[3]);
                }
                else {
                    rawroots[(*numroots)++] = wr[i];
                }
                bool bsmall0=IKabs(ev[0]) > IKabs(ev[3]);
                bool bsmall1=IKabs(ev[0]) > IKabs(ev[1]);
                if( bsmall0 && bsmall1 ) {
                    rawroots[(*numroots)++] = ev[3]/ev[0];
                    rawroots[(*numroots)++] = ev[1]/ev[0];
                }
                else if( bsmall0 && !bsmall1 ) {
                    rawroots[(*numroots)++] = ev[5]/ev[2];
                    rawroots[(*numroots)++] = ev[2]/ev[1];
                }
                else if( !bsmall0 && bsmall1 ) {
                    rawroots[(*numroots)++] = ev[9]/ev[6];
                    rawroots[(*numroots)++] = ev[10]/ev[9];
                }
                else if( !bsmall0 && !bsmall1 ) {
                    rawroots[(*numroots)++] = ev[11]/ev[8];
                    rawroots[(*numroots)++] = ev[11]/ev[10];
                }
            }
        }
    }
}/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void ComputeFk(const IkReal* j, IkReal* eetrans, IkReal* eerot) {
int dummyiter;
for(dummyiter = 0; dummyiter < 1; ++dummyiter) {
IkReal x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17;
x0=IKcos(j[0]);
x1=IKsin(j[1]);
x2=IKcos(j[2]);
x3=IKcos(j[1]);
x4=IKsin(j[2]);
x5=IKsin(j[3]);
x6=IKsin(j[0]);
x7=IKcos(j[3]);
x8=((1.0)*x4);
x9=((0.12)*x3);
x10=((0.06)*x2);
x11=((0.06)*x1);
x12=((0.12)*x1);
x13=((1.0)*x2);
x14=(x4*x6);
x15=(x1*x6);
x16=(x0*x4);
x17=((0.06)*x3*x4);
IkReal x18=(x0*x10);
IkReal x19=(x0*x12);
eetrans[0]=(((x5*((((x18*x3))+(((-1.0)*x11*x16))))))+x19+((x7*((((x1*x18))+(((0.06)*x16*x3))))))+((x19*x2))+((x16*x9)));
IkReal x20=(x12*x6);
eetrans[1]=(((x2*x20))+((x14*x9))+x20+((x7*(((((0.06)*x14*x3))+((x10*x15))))))+((x5*((((x10*x3*x6))+(((-1.0)*x11*x14)))))));
IkReal x21=((1.0)*x4);
eetrans[2]=((0.1699)+x9+((x2*x9))+((x7*((((x10*x3))+(((-1.0)*x11*x21))))))+((x5*(((((-1.0)*x17))+(((-1.0)*x1*x10))))))+(((-1.0)*x12*x21)));
IkReal x22=((1.0)*x8);
if( ((((x5*(((((-1.0)*x22*x3))+(((-1.0)*x1*x13))))))+((x7*(((((-1.0)*x1*x22))+((x13*x3)))))))) < -1-IKFAST_SINCOS_THRESH || ((((x5*(((((-1.0)*x22*x3))+(((-1.0)*x1*x13))))))+((x7*(((((-1.0)*x1*x22))+((x13*x3)))))))) > 1+IKFAST_SINCOS_THRESH )
    continue;
eerot[0]=IKacos((((x5*(((((-1.0)*x22*x3))+(((-1.0)*x1*x13))))))+((x7*(((((-1.0)*x1*x22))+((x13*x3))))))));
return;
}
IKFAST_ASSERT(0);
}

IKFAST_API int GetNumFreeParameters() { return 0; }
IKFAST_API int* GetFreeParameters() { return NULL; }
IKFAST_API int GetNumJoints() { return IKFAST_NUM_JOINTS; }

IKFAST_API int GetIkRealSize() { return sizeof(IkReal); }

IKFAST_API int GetIkType() { return 0x4400000d; }

bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionList * solutions) {
static IkReal j0,cj0,sj0,htj0,j0mul,j1,cj1,sj1,htj1,j1mul,j2,cj2,sj2,htj2,j2mul,j3,cj3,sj3,htj3,j3mul,new_r00,r00,rxp0_0,new_r01,r01,rxp0_1,new_r02,r02,rxp0_2,new_px,px,npx,new_py,py,npy,new_pz,pz,npz,pp;
static unsigned char _ij0[2], _nj0,_ij1[2], _nj1,_ij2[2], _nj2,_ij3[2], _nj3;

j0=FP_NAN; _ij0[0] = -1; _ij0[1] = -1; _nj0 = -1; j1=FP_NAN; _ij1[0] = -1; _ij1[1] = -1; _nj1 = -1; j2=FP_NAN; _ij2[0] = -1; _ij2[1] = -1; _nj2 = -1; j3=FP_NAN; _ij3[0] = -1; _ij3[1] = -1; _nj3 = -1; 
int dummyiter;
for(dummyiter = 0; dummyiter < 1; ++dummyiter) {
    IkSolutionList_Clear(solutions);
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

r00 = eerot[0];
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];
new_px=px;
new_py=py;
new_pz=pz;
new_r00=r00;
r00 = new_r00; px = new_px; py = new_py; pz = new_pz;

pp=((px*px)+(pz*pz)+(py*py));
{
IkReal j0array[2], cj0array[2], sj0array[2];
bool j0valid[2]={false};
_nj0 = 2;
CheckValue x24 = IKatan2WithCheck(((-1.0)*py),px,IKFAST_ATAN2_MAGTHRESH);
if(!x24.valid){
continue;
}
IkReal x23=x24.value;
j0array[0]=((-1.0)*x23);
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
j0array[1]=((3.14159265358979)+(((-1.0)*x23)));
sj0array[1]=IKsin(j0array[1]);
cj0array[1]=IKcos(j0array[1]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
if( j0array[1] > IKPI )
{
    j0array[1]-=IK2PI;
}
else if( j0array[1] < -IKPI )
{    j0array[1]+=IK2PI;
}
j0valid[1] = true;
int ij0;
for(ij0 = 0; ij0 < 2; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
int iij0;
for(iij0 = ij0+1; iij0 < 2; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

static IkReal op[162], zeror[48];
int numroots;;
IkReal x25=((0.5798)*pz);
IkReal x26=((1.0)*pp);
IkReal x27=((-0.4699)+pz);
IkReal x28=((-0.3499)+pz);
IkReal x29=IKcos(j0);
IkReal x30=IKsin(j0);
IkReal x31=((1.0)*pz);
IkReal x32=((0.6796)+(((-4.0)*pz)));
IkReal x33=((0.0998)*pz);
IkReal x34=((0.2299)+(((-1.0)*x31)));
IkReal x35=((0.1099)+(((-1.0)*x31)));
IkReal x36=((-0.1301)+(((-1.0)*x31)));
IkReal x37=((-0.0101)+(((-1.0)*x31)));
IkReal x38=((-0.2299)+pz);
IkReal x39=((-0.1099)+pz);
IkReal x40=((1.0)*(IKcos(r00)));
IkReal x41=((-1.0)+(((-1.0)*x40)));
IkReal x42=((1.0)+(((-1.0)*x40)));
IkReal x43=((-0.3398)+(((2.0)*pz)));
IkReal x44=(px*x29);
IkReal x45=(py*x30);
IkReal x46=((-0.02526601)+(((-1.0)*x26))+(((0.3398)*pz)));
IkReal x47=(x44+x45);
IkReal x48=((((2.0)*x45))+(((2.0)*x44)));
IkReal x49=((((-1.0)*x44))+(((-1.0)*x45)));
IkReal x50=((((0.48)*x44))+(((0.48)*x45)));
IkReal x51=((-1.0)*x48);
op[0]=((-0.05164201)+x25+(((-1.0)*x26)));
op[1]=0;
op[2]=((-0.08044201)+x25+(((-1.0)*x26)));
op[3]=0;
op[4]=0;
op[5]=0;
op[6]=0;
op[7]=0;
op[8]=0;
op[9]=((-0.16441801)+(((0.8198)*pz))+(((-1.0)*x26)));
op[10]=0;
op[11]=0;
op[12]=x50;
op[13]=0;
op[14]=0;
op[15]=x46;
op[16]=0;
op[17]=0;
op[18]=x27;
op[19]=0;
op[20]=x28;
op[21]=0;
op[22]=0.24;
op[23]=0;
op[24]=x39;
op[25]=0;
op[26]=x38;
op[27]=x42;
op[28]=0;
op[29]=x41;
op[30]=0;
op[31]=-4.0;
op[32]=0;
op[33]=x41;
op[34]=0;
op[35]=x42;
op[36]=x27;
op[37]=0;
op[38]=x28;
op[39]=x48;
op[40]=0;
op[41]=x48;
op[42]=x35;
op[43]=0;
op[44]=x34;
op[45]=x49;
op[46]=0.12;
op[47]=x49;
op[48]=0.36;
op[49]=0;
op[50]=0.12;
op[51]=x49;
op[52]=-0.12;
op[53]=x49;
op[54]=x50;
op[55]=0;
op[56]=x50;
op[57]=0;
op[58]=0;
op[59]=0;
op[60]=0;
op[61]=0;
op[62]=0;
op[63]=((((0.96)*x44))+(((0.96)*x45)));
op[64]=0;
op[65]=0;
op[66]=((0.163104)+(((-0.96)*pz)));
op[67]=0;
op[68]=0;
op[69]=0;
op[70]=0;
op[71]=0;
op[72]=x48;
op[73]=0;
op[74]=x48;
op[75]=0;
op[76]=0;
op[77]=0;
op[78]=x48;
op[79]=0;
op[80]=x48;
op[81]=0;
op[82]=-4.0;
op[83]=0;
op[84]=-4.0;
op[85]=0;
op[86]=4.0;
op[87]=0;
op[88]=4.0;
op[89]=0;
op[90]=x48;
op[91]=0;
op[92]=x48;
op[93]=x32;
op[94]=0;
op[95]=x32;
op[96]=x51;
op[97]=0;
op[98]=x51;
op[99]=x43;
op[100]=0;
op[101]=x43;
op[102]=0;
op[103]=0;
op[104]=0;
op[105]=x43;
op[106]=0;
op[107]=x43;
op[108]=((0.02990999)+(((-1.0)*x26))+x33);
op[109]=0;
op[110]=((0.00110999)+(((-1.0)*x26))+x33);
op[111]=0;
op[112]=0;
op[113]=0;
op[114]=0;
op[115]=0;
op[116]=0;
op[117]=((-0.00131401)+(((-1.0)*x26))+(((-0.1402)*pz)));
op[118]=0;
op[119]=0;
op[120]=((-1.0)*x50);
op[121]=0;
op[122]=0;
op[123]=x46;
op[124]=0;
op[125]=0;
op[126]=x36;
op[127]=0;
op[128]=x37;
op[129]=0;
op[130]=0.24;
op[131]=0;
op[132]=x34;
op[133]=0;
op[134]=x35;
op[135]=x41;
op[136]=0;
op[137]=x42;
op[138]=0;
op[139]=4.0;
op[140]=0;
op[141]=x42;
op[142]=0;
op[143]=x41;
op[144]=x36;
op[145]=0;
op[146]=x37;
op[147]=x51;
op[148]=0;
op[149]=x51;
op[150]=x38;
op[151]=0;
op[152]=x39;
op[153]=x47;
op[154]=0.12;
op[155]=x47;
op[156]=0.36;
op[157]=0;
op[158]=0.12;
op[159]=x47;
op[160]=-0.12;
op[161]=x47;
solvedialyticpoly12qep(op,zeror,&numroots);
static IkReal j1array[16], cj1array[16], sj1array[16], j2array[16], cj2array[16], sj2array[16], j3array[16], cj3array[16], sj3array[16];
int numsolutions = 0;
int ij1;
for(ij1 = 0; ij1 < numroots; ij1 += 3)
{
IkReal htj1 = zeror[ij1+0], htj2 = zeror[ij1+1], htj3 = zeror[ij1+2];
if(isnan(htj1)||isnan(htj2)||isnan(htj3)){
continue;
}
j1array[numsolutions]=((2.0)*(atan(htj1)));
j2array[numsolutions]=((2.0)*(atan(htj2)));
j3array[numsolutions]=((2.0)*(atan(htj3)));
if(isinf(htj1)){
cj1array[numsolutions] = IKcos(j1array[numsolutions]);
sj1array[numsolutions] = IKsin(j1array[numsolutions]);
}
else{
IkReal x52=htj1*htj1;
CheckValue x53=IKPowWithIntegerCheck(((1.0)+x52),-1);
if(!x53.valid){
continue;
}
cj1array[numsolutions]=((x53.value)*(((1.0)+(((-1.0)*x52)))));
CheckValue x54=IKPowWithIntegerCheck(((1.0)+(htj1*htj1)),-1);
if(!x54.valid){
continue;
}
sj1array[numsolutions]=((2.0)*htj1*(x54.value));
}
if(isinf(htj2)){
cj2array[numsolutions] = IKcos(j2array[numsolutions]);
sj2array[numsolutions] = IKsin(j2array[numsolutions]);
}
else{
IkReal x55=htj2*htj2;
CheckValue x56=IKPowWithIntegerCheck(((1.0)+x55),-1);
if(!x56.valid){
continue;
}
cj2array[numsolutions]=((x56.value)*(((1.0)+(((-1.0)*x55)))));
CheckValue x57=IKPowWithIntegerCheck(((1.0)+(htj2*htj2)),-1);
if(!x57.valid){
continue;
}
sj2array[numsolutions]=((2.0)*htj2*(x57.value));
}
if(isinf(htj3)){
cj3array[numsolutions] = IKcos(j3array[numsolutions]);
sj3array[numsolutions] = IKsin(j3array[numsolutions]);
}
else{
IkReal x58=htj3*htj3;
CheckValue x59=IKPowWithIntegerCheck(((1.0)+x58),-1);
if(!x59.valid){
continue;
}
cj3array[numsolutions]=((x59.value)*(((1.0)+(((-1.0)*x58)))));
CheckValue x60=IKPowWithIntegerCheck(((1.0)+(htj3*htj3)),-1);
if(!x60.valid){
continue;
}
sj3array[numsolutions]=((2.0)*htj3*(x60.value));
}
if( j1array[numsolutions] > IKPI )
{
    j1array[numsolutions]-=IK2PI;
}
else if( j1array[numsolutions] < -IKPI )
{
    j1array[numsolutions]+=IK2PI;
}
if( j2array[numsolutions] > IKPI )
{
    j2array[numsolutions]-=IK2PI;
}
else if( j2array[numsolutions] < -IKPI )
{
    j2array[numsolutions]+=IK2PI;
}
if( j3array[numsolutions] > IKPI )
{
    j3array[numsolutions]-=IK2PI;
}
else if( j3array[numsolutions] < -IKPI )
{
    j3array[numsolutions]+=IK2PI;
}
numsolutions++;
}
bool j1valid[16]={true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true};
_nj1 = 16;
_nj2 = 1;
_nj3 = 1;
for(ij1 = 0; ij1 < numsolutions; ++ij1)
    {
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
_ij2[0] = 0; _ij2[1] = -1;
_ij3[0] = 0; _ij3[1] = -1;
int iij1;
for(iij1 = ij1+1; iij1 < numsolutions; ++iij1)
{
if( !j1valid[iij1] ) { continue; }
if( IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(cj2array[ij1]-cj2array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj2array[ij1]-sj2array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(cj3array[ij1]-cj3array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj3array[ij1]-sj3array[iij1]) < IKFAST_SOLUTION_THRESH &&  1 )
{
    j1valid[iij1]=false; _ij1[1] = iij1; _ij2[1] = 0; _ij3[1] = 0;  break; 
}
}
    j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];

    j2 = j2array[ij1]; cj2 = cj2array[ij1]; sj2 = sj2array[ij1];

    j3 = j3array[ij1]; cj3 = cj3array[ij1]; sj3 = sj3array[ij1];

{
IkSingleDOFSolution vinfos[4];
IkSingleDOFSolution_Init( vinfos, 4 );
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
vinfos[3].jointtype = 1;
vinfos[3].foffset = j3;
vinfos[3].indices[0] = _ij3[0];
vinfos[3].indices[1] = _ij3[1];
vinfos[3].maxsolutions = _nj3;
int vfree[0];
IkSolutionList_AddSolution(solutions, vinfos, 4, vfree, 0);
}
    }
}
}
}
return IkSolutionList_GetNumSolutions(solutions)>0;
}


IKFAST_API const char* GetKinematicsHash() { return "01a028e65615c8fb2e5c8adcff38c071"; }

IKFAST_API const char* GetIkFastVersion() { return IKFAST_STRINGIZE(IKFAST_VERSION); }


#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char** argv)
{
    if( argc != 12+GetNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",GetNumFreeParameters());
        return 1;
    }

    IkSolutionList solutions;
    IkSolutionList_Init( &solutions );
    IkReal vfree[IKFAST_NUM_FREE_VARS];
    IkReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    size_t i = 0;
    for(i = 0; i < countof(vfree); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ComputeIk(eetrans, eerot, countof(vfree) > 0 ? vfree : NULL, &solutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)IkSolutionList_GetNumSolutions(&solutions));
    IkReal solvalues[IKFAST_NUM_JOINTS];
    for(i = 0; i < IkSolutionList_GetNumSolutions(&solutions); ++i) 
    {
        IkSolution * sol = IkSolutionList_GetSolution(&solutions,i);
        //printf("sol%d (free=%d): ", (int)i, (int)sol.GetFree().size());
        IkReal vsolfree[IKFAST_NUM_JOINTS]; // ?
        IkSolution_GetSolution(sol, solvalues,vsolfree);
        size_t j = 0;
        for( j = 0; j < IKFAST_NUM_JOINTS; ++j)
            printf("%.15f, ", solvalues[j]);
        printf("\n");
    }
    return 0;
}

#endif
