sudo: required
language: c++
cache: ccache
before_install:
  # Clear ccache stats
  - ccache -z
  - ./scripts/travis-install-build-deps.sh
script: ./scripts/travis-build-test.sh
after_success:
  # Show ccache stats
  - ccache -s

notifications:
    email: false
